#!/usr/bin/env bash
# Fetches a kernel that builds none of its drivers in, for the half of
# `zig build test-vm-real-boot` that the Azure Linux kernel cannot exercise.
#
# The VM backend boots the image's own kernel with `rdinit=` and loads whatever
# that kernel needs out of the image's own `lib/modules/<release>`. Azure Linux
# builds ext4, virtio_scsi, sd_mod and virtio_pci in, so a boot on it proves
# only that the built-in path still works. Debian's generic kernel modularizes
# ext4, jbd2, mbcache, virtio_blk, virtio_scsi, sd_mod and virtio_pci -- every
# driver a run needs -- so a guest that comes up on it can only have come up by
# loading them.
#
# The version is pinned rather than resolved from the suite's Packages index. A
# kernel that disappears from the pool should fail this step loudly, not
# silently change what CI proves. When that happens, the same file is still at
# snapshot.debian.org and the pin should be moved deliberately.
#
# Usage: fetch-vm-boot-modular-kernel.sh <destination-directory> [architecture] [prefix]
#
# The architecture defaults to the host's; naming the other one is how the
# cross-architecture boot gets a kernel it can only run under emulation.
#
# Prints three lines on success:
#   <prefix>KERNEL=<path>
#   <prefix>MODULES_BUILTIN=<path>
#   <prefix>MODULE_TREE=<path>
# which can be appended straight to "$GITHUB_ENV". The prefix defaults to
# `VMIZ_VM_BOOT_`.

set -euo pipefail

abi="6.1.0-50"
package_version="6.1.176-1"
base_url="https://deb.debian.org/debian/pool/main/l"

if [ "$#" -lt 1 ] || [ "$#" -gt 3 ]; then
    echo "usage: $0 <destination-directory> [architecture] [prefix]" >&2
    exit 2
fi
destination="$1"
requested_architecture="${2:-$(uname -m)}"
prefix="${3:-VMIZ_VM_BOOT_}"

case "$requested_architecture" in
    x86_64 | amd64) debian_architecture="amd64" ;;
    aarch64 | arm64) debian_architecture="arm64" ;;
    *)
        echo "fetch-vm-boot-modular-kernel: unsupported architecture ${requested_architecture}" >&2
        exit 1
        ;;
esac

release="${abi}-${debian_architecture}"
package="linux-image-${release}"
deb_name="${package}_${package_version}_${debian_architecture}.deb"
deb_url="${base_url}/linux-signed-${debian_architecture}/${deb_name}"

kernel_path="${destination}/boot/vmlinuz-${release}"
module_tree="${destination}/lib/modules/${release}"
modules_builtin_path="${module_tree}/modules.builtin"
modules_dep_path="${module_tree}/modules.dep"

# The tree is pruned to the subtrees a customization run can reach. Keeping the
# whole thing would put 288 MiB of drivers into a test image that has room for
# neither. A subset that turns out to be short of a dependency is not a silent
# pass: the backend refuses the run in preflight and names the module it could
# not find.
keep_subtrees=(
    "kernel/fs/ext4"
    "kernel/fs/jbd2"
    "kernel/fs/mbcache.ko"
    "kernel/lib"
    "kernel/block"
    "kernel/crypto"
    "kernel/drivers/block"
    "kernel/drivers/virtio"
    "kernel/drivers/scsi/scsi_mod.ko"
    "kernel/drivers/scsi/scsi_common.ko"
    "kernel/drivers/scsi/sd_mod.ko"
    "kernel/drivers/scsi/virtio_scsi.ko"
    "kernel/drivers/net/virtio_net.ko"
)

# The caller is expected to wrap this in actions/cache keyed on the version
# above, so a cache hit skips the download entirely.
if [ ! -f "$kernel_path" ] || [ ! -f "$modules_dep_path" ]; then
    for tool in curl ar tar depmod; do
        if ! command -v "$tool" >/dev/null 2>&1; then
            echo "fetch-vm-boot-modular-kernel: ${tool} is required to extract the kernel" >&2
            echo "on Debian and Ubuntu: sudo apt-get install -y binutils kmod" >&2
            exit 1
        fi
    done

    rm -rf "$destination"
    staging="$(mktemp -d)"
    trap 'rm -rf "$staging"' EXIT
    curl -fL -sS --retry 3 -o "${staging}/${deb_name}" "$deb_url"

    # `ar` rather than `dpkg-deb`, so this runs on a non-Debian host too.
    (cd "$staging" && ar p "$deb_name" data.tar.xz > data.tar.xz.out && mv data.tar.xz.out data.tar.xz)
    mkdir -p "${staging}/root"
    tar -xJf "${staging}/data.tar.xz" -C "${staging}/root" \
        "./boot/vmlinuz-${release}" \
        "./lib/modules/${release}"

    # Debian ships no modules.dep: it is generated by depmod in the package's
    # postinst, which never runs here. Generating it before pruning is what
    # makes it the kernel's own dependency graph rather than an invention.
    depmod -b "${staging}/root" "$release"

    mkdir -p "$module_tree" "${destination}/boot"
    cp "${staging}/root/boot/vmlinuz-${release}" "$kernel_path"
    for metadata in modules.dep modules.builtin; do
        cp "${staging}/root/lib/modules/${release}/${metadata}" "${module_tree}/${metadata}"
    done
    for subtree in "${keep_subtrees[@]}"; do
        source_path="${staging}/root/lib/modules/${release}/${subtree}"
        if [ ! -e "$source_path" ]; then
            echo "fetch-vm-boot-modular-kernel: ${subtree} is not in this kernel" >&2
            exit 1
        fi
        mkdir -p "$(dirname "${module_tree}/${subtree}")"
        cp -r "$source_path" "${module_tree}/${subtree}"
    done
fi

for required in "$kernel_path" "$modules_builtin_path" "$modules_dep_path"; do
    if [ ! -f "$required" ]; then
        echo "fetch-vm-boot-modular-kernel: ${required} was not produced" >&2
        exit 1
    fi
done

# The point of this kernel is what it does *not* build in. A Debian rebuild that
# quietly started building ext4 or the virtio drivers in would leave CI passing
# while proving nothing, so it is checked rather than assumed.
for driver in ext4 virtio_blk virtio_scsi virtio_pci sd_mod; do
    if grep -qE "/${driver}\.ko\$" "$modules_builtin_path"; then
        echo "fetch-vm-boot-modular-kernel: ${driver} is built into ${release}," >&2
        echo "so this kernel no longer exercises the loadable-driver path" >&2
        exit 1
    fi
    if ! grep -qE "^kernel/.*/${driver}\.ko:" "$modules_dep_path"; then
        echo "fetch-vm-boot-modular-kernel: ${driver} is not in ${release}'s module tree" >&2
        exit 1
    fi
done

echo "${prefix}KERNEL=$(readlink -f "$kernel_path")"
echo "${prefix}MODULES_BUILTIN=$(readlink -f "$modules_builtin_path")"
echo "${prefix}MODULE_TREE=$(readlink -f "$module_tree")"
